-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO07_3;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO07_3;

-- CONECTANDO BANCO DE DADOS
USE DBEXERCICIO07_3;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,PRIMARY KEY (IDALUNO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL
    ,DESCRICAO VARCHAR(100) NOT NULL
    ,PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE COMPRAR (
	IDALUNO INT NOT NULL
    ,IDPRODUTO INT NOT NULL
    ,PRIMARY KEY (IDALUNO, IDPRODUTO)
	,FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
    ,FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
);