-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO07_2;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO07_2;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO07_2;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL
    ,NOME VARCHAR(100)
    ,PRIMARY KEY (IDALUNO)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL
    ,DTPEDIDO DATE
    ,PRODUTO VARCHAR(50)
    ,IDALUNO INT NOT NULL
    ,PRIMARY KEY (IDPEDIDO)
    ,FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);