-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_8;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_8;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_8;

-- CRIANDO AS TABELAS
CREATE TABLE COMPUTADOR (
	IDCOMPUTADOR INT NOT NULL
    ,MARCA VARCHAR(20)
    ,MODELO VARCHAR(30)
    ,PRIMARY KEY (IDCOMPUTADOR)
);

CREATE TABLE CHAMADA (
	IDCHAMADA INT NOT NULL
    ,NOME_SOLICITANTE VARCHAR(100) 
    ,DESCRICAO VARCHAR(120)
    ,DATA_CHAMADA DATE NOT NULL
    ,HORA_CHAMADA TIME NOT NULL
    ,IDCOMPUTADOR INT NOT NULL
    ,PRIMARY KEY (IDCHAMADA)
    ,FOREIGN KEY (IDCOMPUTADOR) REFERENCES COMPUTADOR (IDCOMPUTADOR)
);