-- APAGANDO O BANCO DE DADOS CASO EXISTIR
DROP DATABASE IF EXISTS DBEXEMPLO_02;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXEMPLO_02;

-- CONECTANDO NA BASE DE DADOS
USE DBEXEMPLO_02;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL
	,NOME VARCHAR(120)
    ,DTNASCIMENTO DATE
    ,RUA VARCHAR(100)
    ,NUMERO INT
    ,COMPLEMENTE VARCHAR(100)
    ,BAIRRO VARCHAR(100)
    ,CIDADE VARCHAR(100)
    ,ESTADO CHAR(2)
    ,CEP CHAR(8)
    ,primary key (IDCLIENTE)
);
    