-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_17;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_17;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_17;

-- CRIANDO AS TABELAS
CREATE TABLE NIVEL (
	IDNIVEL INT NOT NULL
    ,NOME VARCHAR(100)
    ,VALOR VARCHAR(3)
    ,PRIMARY KEY (IDNIVEL)
);

CREATE TABLE OFICINA (
	IDOFICINA INT NOT NULL
    ,ASSUNTO VARCHAR(200)
    ,NOME VARCHAR(100)
    ,IDNIVEL INT NOT NULL
    ,PRIMARY KEY (IDOFICINA)
    ,FOREIGN KEY (IDNIVEL) REFERENCES NIVEL (IDNIVEL)
);

CREATE TABLE PARTICIPANTE (
	IDPARTICIPANTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,EMAIL VARCHAR(120)
    ,PRIMARY KEY (IDPARTICIPANTE)
);

CREATE TABLE INSCRICAO (
	IDINSCRICAO INT NOT NULL
	,DTINSCRICAO DATE
    ,HRINCRICAO TIME
    ,IDOFICINA INT NOT NULL
    ,IDPARTICIPANTE INT NOT NULL
    ,PRIMARY KEY (IDINSCRICAO)
    ,FOREIGN KEY (IDOFICINA) REFERENCES OFICINA (IDOFICINA)
    ,FOREIGN KEY (IDPARTICIPANTE) REFERENCES PARTICIPANTE (IDPARTICIPANTE)
);
