
DROP DATABASE IF EXISTS ATIVIDADE_02;

CREATE DATABASE ATIVIDADE_02;

USE ATIVIDADE_02;

CREATE TABLE ESTANTE(
	IDLIVRO INT NOT NULL
	,TITULO VARCHAR(120) NOT NULL
    ,AUTOR VARCHAR(120) NOT NULL
    ,EDITORA VARCHAR(120)
    ,ANO_DE_PUBLICACAO CHAR(4) NOT NULL
    ,primary key (IDLIVRO)
);