-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO07_1;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO07_1;

-- CONECTANDO BANCO DE DADOS
USE DBEXERCICIO07_1;

-- CRIANDO AS TABELAS
CREATE TABLE PESSOA_PASSAPORTE (
	IDPESSOA INT NOT NULL
    , IDPASSAPORTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,NUMERO VARCHAR(20)
    ,PRIMARY KEY (IDPESSOA, IDPASSAPORTE)
);