-- TABELA DE CANDIDATO (1)
DROP TABLE CANDIDATO;

-- TABELA DE PARTIDO (1)
DROP TABLE PARTIDO;

-- TABELA DE DEPARTAMENTO (1)
CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
);

-- TABELA DE SETOR (1)
DROP TABLE SETOR;

-- TABELA DE FUNCIONARIO (9)
ALTER TABLE FUNCIONARIO
ADD DROP COLUMN FUNCIONARIO,
DROP COLUMN DESCRICAO,
DROP COLUMN IDPARTIDO,
ADD COLUMN IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
ADD COLUMN NOME VARCHAR(100),
ADD COLUMN CPF CHAR (11),
ADD COLUMN SENHA VARCHAR(45),
ADD COLUMN IDDEPARTAMENTO INT,
ADD FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO);

-- TABELA DE CARGO (1)
CREATE TABLE CARGO(
	IDCARGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, DESCRICAO VARCHAR(100)
);

-- TABELA DE FUNCAO (1)
DROP TABLE FUNCAO;

-- TABELA DE CHAPA (1)
CREATE TABLE CHAPA (
	IDCHAPA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDELEICAO INT NOT NULL,
	NOME VARCHAR(100),
	FOREIGN KEY (IDELEICAO) REFERENCES ELEICAO(IDELEICAO)
);


-- TABELA DE PARTICIPA (9)
ALTER TABLE PARTICIPA
DROP COLUMN IDUSUARIO,
DROP COLUMN IDFUNCAO,
ADD COLUMN IDFUNCIONARIO INT,
ADD COLUMN IDCHAPA INT,
ADD COLUMN IDCARGO INT ,
ADD PRIMARY KEY (IDFUNCIONARIO, IDCHAPA),
ADD FOREIGN KEY (IDCARGO) REFERENCES CARGO(IDCARGO)
ADD FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
ADD FOREIGN KEY (IDCHAPA) REFERENCES CHAPA(IDCHAPA),


-- TABELA DE VOTO (8)
ALTER TABLE VOTAR 
drop primary key,
DROP COLUMN IDUSUARIO,
DROP COLUMN IDCANDIDATO,
ADD COLUMN IDFUNCIONARIO INT,
ADD COLUMN IDCHAPA INT,
ADD PRIMARY KEY (IDELEICAO, IDFUNCIONARIO),
ADD FOREIGN KEY (IDELEICAO) REFERENCES ELEICAO(IDELEICAO),
ADD FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
ADD FOREIGN KEY (IDCHAPA) REFERENCES CHAPA(IDCHAPA),





