DROP DATABASE IF EXISTS DBELEICAO;

CREATE DATABASE DBELEICAO;

USE DBELEICAO;

CREATE TABLE PARTIDO(
	IDPARTIDO INT PRIMARY KEY,
	NOME VARCHAR(255),
	SIGLA VARCHAR(10)
);

CREATE TABLE CANDIDATO(
	IDCANDIDADTO INT NOT NULL,
	IDPARTIDO INT, 
	NOME VARCHAR(255),
	RUA VARCHAR(100),
	CEP VARCHAR(8),
	CIDADE VARCHAR(100),
	ESTADO CHAR(2),
	FOREIGN KEY (IDPARTIDO) REFERENCES PARTIDO(IDPARTIDO)
);

CREATE TABLE FUNCIONARIO (
	FUNCIONARIO INT PRIMARY KEY,
	IDPARTIDO INT NOT NULL,
	DESCRICAO VARCHAR (100)
);

CREATE TABLE USUARIO (
  LOGIN VARCHAR(100),
  SENHA VARCHAR(255),
  EMAIL VARCHAR(100)
);

CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL,
	NOME VARCHAR(100)
);

CREATE TABLE CARGO(
	DESCRICAO VARCHAR(100)
);

CREATE TABLE PARTICIPA(
	IDCARGO INT,
	IDUSUARIO INT
);

CREATE TABLE VOTAR(
	IDELEICAO INT PRIMARY KEY,
	IDUSUARIO INT,
	IDCANDIDATO INT,
	DT_VOTO DATETIME
);

CREATE TABLE ELEICAO (
	IDELEICAO INT NOT NULL,
	TITULO VARCHAR(100),
	DT_INICIO DATETIME,
	DT_FIM DATETIME,
	PRIMARY KEY (IDELEICAO)
);

CREATE TABLE CHAPA(
	IDCHAPA INT NOT NULL
    ,IDELEICAO INT NOT NULL
    ,NOME VARCHAR(100)
    ,PRIMARY KEY (IDCHAPA)
    ,FOREIGN KEY (IDELEICAO) REFERENCES ELEICAO (IDELEICAO)
);

DROP TABLE cANDIDATO;

DROP TABLE PARTIDO;

ALTER TABLE DEPARTAMENTO
	ADD PRIMARY KEY (IDDEPARTAMENTO);

ALTER TABLE FUNCIONARIO
	DROP COLUMN IDPARTIDO
    ,DROP COLUMN DESCRICAO
    ,ADD COLUMN NOME VARCHAR(100)
    ,ADD COLUMN CPF CHAR(11)
    ,ADD COLUMN SENHA VARCHAR(45)
    ,ADD COLUMN IDDEPARTAMENTO INT NOT NULL
    ,ADD FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO);

ALTER TABLE CARGO
	ADD COLUMN IDCARGO INT NOT NULL
    ,ADD PRIMARY KEY (IDCARGO);

ALTER TABLE PARTICIPA
	DROP COLUMN IDUSUARIO
    ,ADD COLUMN IDDEPARTAMENTO INT NOT NULL
    ,ADD COLUMN IDCHAPA INT NOT NULL
    ,ADD PRIMARY KEY (IDCHAPA, IDDEPARTAMENTO, IDCARGO)
    ,ADD FOREIGN KEY (IDCHAPA) REFERENCES CHAPA (IDCHAPA)
    ,ADD FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)
    ,ADD FOREIGN KEY (IDCARGO) REFERENCES CARGO (IDCARGO);

DROP TABLE USUARIO;
