-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_18;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_18;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_18;

-- CRIANDO AS TABELAS
CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO INT NOT NULL
    ,TELEFONE INT
    ,NOME VARCHAR(150)
    ,PRIMARY KEY (IDDEPARTAMENTO)
);

create table FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL
    ,NOME VARCHAR(100)
    ,DTADMISSAO DATETIME
    ,TELEFONE INT
    ,IDDEPARTAMENTO INT NOT NULL
    ,PRIMARY KEY (IDFUNCIONARIO)
    ,FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)
);
