-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_14;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_14;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_14;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL
    ,NOME VARCHAR(100)
    ,SENHA VARCHAR(10)
    ,CPF VARCHAR(11)
    ,EMAIL VARCHAR(100)
    ,PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE AMBIENTE (
	IDAMBIENTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,IDUSUARIO INT NOT NULL
    ,PRIMARY KEY (IDAMBIENTE)
    ,FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE DISPOSITIVO (
	IDDISPOSITIVO INT NOT NULL
    ,NOME VARCHAR(100)
    ,CODIGO_ID int
    ,IDUSUARIO INT NOT NULL
    ,IDAMBIENTE INT NOT NULL
    ,PRIMARY KEY (IDDISPOSITIVO)
    ,FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
    ,FOREIGN KEY (IDAMBIENTE) REFERENCES AMBIENTE (IDAMBIENTE)
);