-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_11;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_11;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_11;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL
    ,NOME VARCHAR(100)
    ,LOGIN VARCHAR(45)
    ,SENHA VARCHAR(15)
    ,DTCADASTRO DATE
    ,PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO(
	IDVIDEO INT NOT NULL
    ,TITUTLO VARCHAR(45)
    ,CATEGORIA VARCHAR(45)
    ,DTPUBLICACAO DATE
    ,PRIMARY KEY (IDVIDEO)
);

CREATE TABLE ACESSAR(
	IDUSUARIO INT NOT NULL
    ,IDVIDEO INT NOT NULL
    ,PRIMARY KEY (IDUSUARIO, IDVIDEO)
    ,FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
    ,FOREIGN KEY (IDVIDEO) REFERENCES VIDEO (IDVIDEO)
);
