SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	SEXO ENUM ('M', 'F'),
	IDADE int,
	CIDADE VARCHAR(20)
);


-- 1.	Crie os comandos SQL para inserir os dados informados na tabela 1.

INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ANDERSON', 17, 'M','PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CESAR', 21, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DIEGO', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GABRIEL', 19, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOAO', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LEONARDO', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCAS', 20, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PRISCILA', 19, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RENATA', 21, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARIA', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TANIA', 19, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOSE', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARISA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOANA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ALICE', 21, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TADEU', 18, 'M', 'TUBARAO');

-- QUESTAO 1
SELECT * FROM ALUNO WHERE SEXO = 'M';

-- QUESTAO 2
SELECT * FROM ALUNO WHERE IDADE = 19;

-- QUESTAO 3
SELECT * FROM ALUNO WHERE NOME LIKE 'D%';

-- QUESTAO 4
SELECT *FROM ALUNO WHERE IDADE BETWEEN 20 AND 22;

-- QUESTAO 5
SELECT * FROM ALUNO WHERE CIDADE IS NULL;

-- QUESTAO 6
SELECT * FROM ALUNO WHERE CIDADE = 'BLUMENAU';

-- QUESTAO 7
SELECT * FROM ALUNO WHERE IDADE <> 18;

-- QUESTAO 8
SELECT * FROM ALUNO WHERE NOME LIKE '%RI%';

-- QUESTAO 9
SELECT * FROM ALUNO WHERE CIDADE = 'SAO JOSE' AND SEXO = 'M' AND IDADE < 20;

-- QUESTAO 10
SELECT * FROM ALUNO WHERE (IDADE > 20 AND SEXO = 'F') OR (IDADE > 17 AND SEXO = 'M');

-- QUESTAO 11
SELECT * FROM ALUNO WHERE NOME LIKE '%A%' AND NOME LIKE '%R%';

-- QUESTAO 12
SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';

-- QUESTAO 13
SELECT IDALUNO, NOME FROM ALUNO WHERE CIDADE = 'BLUMENAU';

-- QUESTAO 14
SELECT NOME, CIDADE FROM ALUNO WHERE (IDADE > 20 AND SEXO = 'F') OR (IDADE > 17 AND SEXO = 'M');

-- QUESTAO 15
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE BETWEEN 15 AND 18;

-- QUESTAO 16
SELECT CIDADE FROM ALUNO WHERE CIDADE IS NOT NULL;

-- QUESTAO 17
SELECT NOME FROM ALUNO WHERE (IDADE = 18 AND CIDADE = 'PALHOCA') OR (IDADE = 17 AND CIDADE = 'SAO JOSE');

-- QUESTAO 18
SELECT NOME FROM ALUNO WHERE SEXO = 'M' AND CIDADE = 'TUBARAO' AND IDADE BETWEEN 18 AND 25;

-- QUESTAO 19
SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;

-- QUESTAO 20
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;

-- QUESTAO 21
SELECT * FROM ALUNO ORDER BY IDADE DESC;
SELECT * FROM ALUNO ORDER BY NOME;

-- QUESTAO 22
SELECT * FROM ALUNO ORDER BY SEXO;
SELECT * FROM ALUNO ORDER BY NOME;

-- QUESTAO 23
UPDATE ALUNO SET IDADE = 20 WHERE NOME = 'JOSE';

-- QUESTAO 24
UPDATE ALUNO SET IDADE = 21 WHERE NOME IN ('TADEU', 'CESAR', 'MARISA');

-- QUESTAO 25
UPDATE ALUNO SET NOME = 'LUIZ', IDADE = 22, SEXO = 'M', CIDADE = 'TIJUCAS' WHERE IDALUNO = 12;

-- QUESTAO 26
UPDATE ALUNO SET CIDADE = NULL WHERE IDADE > 24;

-- QUESTAO 27
DELETE FROM ALUNO WHERE CIDADE IS NULL;

-- QUESTAO 28
DELETE FROM ALUNO WHERE CIDADE = 'TUBARAO' AND IDADE > 15 AND SEXO = 'M';

-- QUESTAO 29
DELETE FROM ALUNO WHERE NOME IN ('TADEU', 'ALICE', 'MARIA') AND IDADE = 19;

-- QUESTAO 30
DELETE FROM ALUNO WHERE (IDADE < 18 AND SEXO = 'M') OR (IDADE < 21 AND SEXO = 'F');
SELECT * FROM ALUNO;