SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTATISTICA;

CREATE DATABASE DBESTATISTICA;

USE DBESTATISTICA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, SEXO CHAR(1)
);

CREATE TABLE ESTATISTICA (	
	HOMEM INT
	, MULHER INT
);

INSERT INTO ESTATISTICA(HOMEM, MULHER)VALUES(0,0);

DELIMITER $$
CREATE TRIGGER PESSOA_INSERT AFTER INSERT ON PESSOA FOR EACH ROW
BEGIN

	IF NEW.SEXO = 'F' THEN
		UPDATE ESTATISTICA
        SET MULHER = MULHER + 1;
	END IF;
    
    IF NEW.SEXO = 'M' THEN
		UPDATE ESTATISTICA
        SET HOMEM = HOMEM + 1;
	END IF;

END $$

CREATE TRIGGER PESSOA_DELETE AFTER DELETE ON PESSOA FOR EACH ROW
BEGIN

	IF OLD.SEXO = 'F' THEN
		UPDATE ESTATISTICA
        SET MULHER = MULHER - 1;
	END IF;
    
    IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA
        SET HOMEM = HOMEM - 1;
	END IF;

END $$

CREATE TRIGGER PESSOA_UPDATE AFTER UPDATE ON PESSOA FOR EACH ROW
BEGIN

    -- REMOVENDO ANTIGO
	IF OLD.SEXO = 'F' THEN
		UPDATE ESTATISTICA
        SET MULHER = MULHER - 1;
	END IF;
    
    IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA
        SET HOMEM = HOMEM - 1;
	END IF;
    
    -- ADICIONANDO NOVO
    IF NEW.SEXO = 'F' THEN
		UPDATE ESTATISTICA
        SET MULHER = MULHER + 1;
	END IF;
    
    IF NEW.SEXO = 'M' THEN
		UPDATE ESTATISTICA
        SET HOMEM = HOMEM + 1;
	END IF;

END $$


DELIMITER ;

INSERT INTO PESSOA (NOME, SEXO) VALUES ('MARIA', 'M');
INSERT INTO PESSOA (NOME, SEXO) VALUES ('PEDRO', 'M');
INSERT INTO PESSOA (NOME, SEXO) VALUES ('ANA', 'F');
INSERT INTO PESSOA (NOME, SEXO) VALUES ('JOAO', 'M');
INSERT INTO PESSOA (NOME, SEXO) VALUES ('MARIO', 'M');
SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA;

DELETE FROM PESSOA WHERE IDPESSOA = 5;
SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA;

UPDATE PESSOA SET SEXO = 'F' WHERE NOME = 'MARIA';
SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA;






