-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_19;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_19;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_19;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,EMAIL VARCHAR(150)
    ,CPF CHAR(13)
    ,DDD_TELEFONE_CELULAR varchar(3)
    ,TELEFONE_CELULAR INT
    ,DDD_TELEFONE_RESIDENCIAL varchar(3)
    ,TELEFONE_RESIDENCIAL INT
    ,DDD_TELEFONE_REFERENCIAL varchar(3)
    ,TELEFONE_REFERENCIAL INT
    ,ENDERECO_RUA VARCHAR(60)
    ,ENDERECO_NUMERO VARCHAR(5)
    ,ENDERECO_COMPLEMENTO VARCHAR(45)
    ,ENDERECO_BAIRRO VARCHAR(45)
    ,ENDERECO_CIDADE VARCHAR(45)
    ,ENDERECO_ESTADO VARCHAR(45)
    ,ENDERECO_CEP VARCHAR(10)
    ,NUMERO_CNH VARCHAR(12)
    ,PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE VEICULO(
	IDVEICULO INT NOT NULL
    ,MARCA VARCHAR(45)
    ,MODELO VARCHAR(45)
    ,ANO_MODELO DATETIME
    ,ANO_FABRICACAO DATETIME
    ,TIPO_COMBUSTIVEL VARCHAR(45)
    ,PRIMARY KEY (IDVEICULO)
);

CREATE TABLE LOCACAO (
	IDLOCACAO INT NOT  NULL
    ,DATA_E_HORA_LOCACAO DATETIME
    ,DATA_E_HORA_ENTREGA DATETIME
    ,KM_LOCACAO VARCHAR(10)
    ,KM_ENTREGA VARCHAR(10)
    ,IDCLIENTE INT NOT NULL
    ,IDVEICULO INT NOT NULL
    ,PRIMARY KEY (IDLOCACAO)
    ,FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    ,FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO)
);

CREATE TABLE OPCIONAL (
	IDOPCIONAL INT NOT NULL
    ,AR_CONDICIONAL VARCHAR(5)
    ,DIRECAO_HIDRAULICA VARCHAR(5)
    ,TRAVA_ELETRICA VARCHAR(5)
    ,PRIMARY KEY (IDOPCIONAL)
);

CREATE TABLE OPICIONAL_VEICULO (
	IDOPCIONAL INT NOT NULL
    ,IDVEICULO INT NOT NULL
    ,PRIMARY KEY (IDOPCIONAL, IDVEICULO)
    ,FOREIGN KEY (IDOPCIONAL) REFERENCES OPCIONAL (IDOPCIONAL)
    ,FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO)
);