// feito em DESI_2022_2_N!





// Exemplo if

//let nota = 6;

// if (nota >= 0 && nota <= 10){

//     if (nota >= 7){

//         console.log("Aprovado!")

//     }else if (nota < 6) {

//         console.log("Reprovado!")

//     }else {

//         console.log("Recuperação!")

//     }

// }else{

//     console.log("Digite uma nota valida!")

// }





// Exemplo for

//let nota = 5

// for(i=nota; i <= 7; i++){

//     if (i >= 0 && i <= 10){

//         if (i >= 7){

//             console.log("Aprovado!")

//         }else if (i < 6) {

//             console.log("Aguarde...")

//         }else {

//             console.log("Aguarde...")

//         }

//     }else{

//         console.log("Digite uma nota valida!")

//     }
// }





// Exemplo de for simples

// for(i=0; i <= 10; i++){

//     console.log(i)

// }





// Exemplo de switch

let diaDaSemana = new Date().getDay()

switch(diaDaSemana){

    case 0:
        console.log("Domingo!")
        break;

    case 1:
        console.log("Segunda-feira!")
        break;

    case 2:
        console.log("Terça-feira!")
        break;

    case 3:
        console.log("Quarta-feira!")
        break;

    case 4:
        console.log("Quinta-feira!")
        break;

    case 5:
        console.log("Sexta-feira!")
        break;
    
    case 6:
        console.log("Sábado!")
        break;

}
