
DROP DATABASE IF EXISTS ATIVIDADE_03;

CREATE DATABASE ATIVIDADE_03;

USE ATIVIDADE_03;

CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL
	,NOME VARCHAR(120) NOT NULL
    ,DTNASCIMENTO VARCHAR(120) NOT NULL
    ,CELULAR_DDD VARCHAR(5)
    ,TELEFONE_CELULAR VARCHAR(15)
    ,RESIENCIAL_DDD VARCHAR(5)
    ,TELEFONE_RESIDENCIAL VARCHAR(15)
    ,CONTATO_DDD VARCHAR(5)
    ,TELEFONE_CONTATO VARCHAR(15)
    ,NOME_COM_CELULAR VARCHAR(120)
    ,primary key (IDALUNO)
);