-- APAGANDO O BANCO DE DADOS SE EXISTIR
DROP DATABASE IF EXISTS DBEXERCICIO01;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO01;

-- CONECTANDO NO BANCO DE DADOS
USE DBEXERCICIO01;

-- CRIANDO AS TABELAS DO BANCO DE DADOS
CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL
	, NOME VARCHAR(160) NOT NULL
	, TELEFONE VARCHAR(15)
	, EMAIL VARCHAR(160)
	, PRIMARY KEY (IDPESSOA)
);

-- INCLUINDO UM DADO NA TABELA
INSERT INTO PESSOA(IDPESSOA ,NOME)
VALUES(1, 'KAUAM');

-- EXEMPLO DE CONSULTA
SELECT * FROM PESSOA;

-- EXEMPLO DE ALTERAR
UPDATE PESSOA SET EMAIL = 'KAUAMLUIZ' WHERE IDPESSOA = 1;
UPDATE PESSOA SET EMAIL = NULL WHERE IDPESSOA = 1;

-- EXEMPLO DE DELETAR
DELETE FROM PESSOA WHERE IDPESSOA = 1;

