-- APAGANDO O BANCO DE DADOS SE EXISTIR
DROP DATABASE IF EXISTS DBEXERCICIO01;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO01;

-- CONECTANDO NO BANCO DE DADOS
USE DBEXERCICIO01;

-- CRIANDO AS TABELAS DO BANCO DE DADOS
CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL
	, NOME VARCHAR(160) NOT NULL
	, TELEFONE VARCHAR(15)
	, EMAIL VARCHAR(160)
	, PRIMARY KEY (IDPESSOA)
);

