-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_9;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_9;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_9;

-- CRIANDO AS TABELAS
CREATE TABLE REGISTRAR(
	IDVEICULO INT NOT NULL
    ,MODELO VARCHAR(45)
    ,MARCA VARCHAR(45)
    ,ANO_FABRICACAO YEAR
    ,PLACA VARCHAR(9)
    ,IDDOCUMENTO INT NOT NULL
    ,RENAVAM VARCHAR(11)
    ,DTREGISTRO DATE 
    ,CIDADE VARCHAR(45)
    ,ESTADO_REGISTRO VARCHAR(45)
    ,PRIMARY KEY (IDVEICULO, IDDOCUMENTO)
);
