-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_13_C;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_13_C;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_13_C;

-- CRIANDO AS TABELAS
CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE MEDICO (
	IDMEDICO INT NOT NULL
    ,NOME VARCHAR(100)
    ,PRIMARY KEY (IDMEDICO)
);

CREATE TABLE CONSULTA (
	IDCONSULTA INT NOT NULL
    ,IDPACIENTE INT NOT NULL
    ,IDMEDICO INT NOT NULL
    ,DTCONSULTA DATETIME
    ,PRIMARY KEY (IDCONSULTA)
    ,FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
    ,FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);
