// calcular raio
//let raio = prompt('Digite o raio')
//raio = Number(raio)

// calcular area
//let area1 = 3.14 * raio**2

// mostrar resultado
//alert('A area é: ' + area1)

//ler base do triangulo
let base = prompt('Digite o base')
base = Number(base)
    
// calcular altura do triangulo
let altura = prompt('Digite a altura')
altura = Number(altura)

// calcular area do triangulo
let area = (base * altura)/2
alert('A sua area é: ' + area)

// nome e sobrenome
let nome = prompt('digite seu nome')
let sobrenome = prompt('digite seu sobrenome')
let usuario = nome + sobrenome

alert('seu nome completo é: ' + nome+ ' ' + sobrenome)
