SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBATIVIDADE_34;

CREATE DATABASE DBATIVIDADE_34;

USE DBATIVIDADE_34;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, IDADE INT
);

CREATE TABLE CLASSIFICACAO (	
	CRIANCA INT
	, JOVEM INT
    , ADULTO INT
);

INSERT INTO CLASSIFICACAO (CRIANCA, JOVEM, ADULTO)VALUES(0, 0, 0);

DELIMITER $$
CREATE TRIGGER ALUNO_INSERT AFTER INSERT ON ALUNO FOR EACH ROW
BEGIN

	IF NEW.IDADE < 12 THEN
		UPDATE CLASSIFICACAO
		SET CRIANCA = CRIANCA + 1;
	END IF;
    
    IF NEW.IDADE BETWEEN 12 AND 18 THEN
		UPDATE CLASSIFICACAO
		SET JOVEM = JOVEM + 1;
	END IF;
    
    IF NEW.IDADE > 18 THEN
		UPDATE CLASSIFICACAO
		SET ADULTO = ADULTO + 1;
	END IF;

END $$

CREATE TRIGGER ALUNO_DELETE AFTER DELETE ON ALUNO FOR EACH ROW
BEGIN

	
	IF OLD.IDADE < 12 THEN
		UPDATE CLASSIFICACAO
		SET CRIANCA = CRIANCA - 1;
	END IF;
    
    IF OLD.IDADE BETWEEN 12 AND 18 THEN
		UPDATE CLASSIFICACAO
		SET JOVEM = JOVEM - 1;
	END IF;
    
    IF OLD.IDADE > 18 THEN
		UPDATE CLASSIFICACAO
		SET ADULTO = ADULTO - 1;
	END IF;

END $$

CREATE TRIGGER ALUNO_UPDATE AFTER UPDATE ON ALUNO FOR EACH ROW
BEGIN

	
	IF OLD.IDADE < 12 THEN
		UPDATE CLASSIFICACAO
		SET CRIANCA = CRIANCA - 1;
	END IF;
    
    IF OLD.IDADE BETWEEN 12 AND 18 THEN
		UPDATE CLASSIFICACAO
		SET JOVEM = JOVEM - 1;
	END IF;
    
    IF OLD.IDADE > 18 THEN
		UPDATE CLASSIFICACAO
		SET ADULTO = ADULTO - 1;
	END IF;
    
    IF NEW.IDADE < 12 THEN
		UPDATE CLASSIFICACAO
		SET CRIANCA = CRIANCA + 1;
	END IF;
    
    IF NEW.IDADE BETWEEN 12 AND 18 THEN
		UPDATE CLASSIFICACAO
		SET JOVEM = JOVEM + 1;
	END IF;
    
    IF NEW.IDADE > 18 THEN
		UPDATE CLASSIFICACAO
		SET ADULTO = ADULTO + 1;
	END IF;

END $$
DELIMITER ;

INSERT INTO ALUNO (NOME, IDADE) VALUES ('MARIA', 12);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('PEDRO', 16);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('ANA', 25);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('JOAO', 10);
INSERT INTO ALUNO (NOME, IDADE) VALUES ('MARIO', 17);
SELECT * FROM ALUNO;
SELECT * FROM CLASSIFICACAO;

DELETE FROM ALUNO WHERE IDALUNO = 5;
SELECT * FROM ALUNO;
SELECT * FROM CLASSIFICACAO;

UPDATE ALUNO SET IDADE = 19 WHERE NOME = 'MARIA';
SELECT * FROM ALUNO;
SELECT * FROM CLASSIFICACAO;






