
DROP DATABASE IF EXISTS ATIVIDADE_01;

CREATE DATABASE ATIVIDADE_01;

USE ATIVIDADE_01;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL
	,NOME VARCHAR(120)
    ,MARCA VARCHAR(20) NOT NULL
    ,MODELO VARCHAR(20) NOT NULL
    ,ANO_DE_FABRICACAO CHAR(4)
    ,ANO_DE_MODELO CHAR(4)
    ,PLACA CHAR(9) NOT NULL
    ,COR VARCHAR(20)
    ,NUMERO_DE_CHASSI CHAR(3) NOT NULL
    ,primary key (IDCLIENTE)
);
    