-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_16;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_16;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_16;

-- CRIANDO AS TABELAS
CREATE TABLE FILIAL (
	IDFILIAL INT NOT NULL
    ,NOME VARCHAR(100)
    ,TELEFONE INT
    ,PRIMARY KEY (IDFILIAL)
);

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL
    ,NOME VARCHAR(100)
    ,DTADMISSAO DATE
    ,IDFILIAL INT NOT NULL
    ,PRIMARY KEY (IDFUNCIONARIO)
    ,FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL
    ,NOME VARCHAR(100)
    ,EMAIL VARCHAR(150)
    ,IDFILIAL INT NOT NULL
    ,PRIMARY KEY (IDCLIENTE)
    ,FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
);

CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL
    ,TITULO VARCHAR(100)
    ,DESCRICAO VARCHAR(200)
    ,IDCLIENTE INT NOT NULL
    ,PRIMARY KEY (IDPROJETO)
    ,FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TRABALHAR (
	IDFUNCIONARIO INT NOT NULL
    ,IDPROJETO INT NOT NULL
    ,PRIMARY KEY (IDFUNCIONARIO, IDPROJETO)
    ,FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
    ,FOREIGN KEY (IDPROJETO) REFERENCES PROJETO (IDPROJETO)
);
