-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS ATIVIDADE_10;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE ATIVIDADE_10;

-- CONECTANDO BANCO DE DADOS
USE ATIVIDADE_10;

-- CRIANDO AS TABELAS
CREATE TABLE PEDIDO(
	IDPEDIDO INT NOT NULL
    ,DTPEDIDO DATE
    ,HORA_PEDIDO TIME 
    ,NOME_CLIENTE VARCHAR(100)
    ,PRIMARY KEY (IDPEDIDO)
);

CREATE TABLE PRODUTO(
	IDPRODUTO INT NOT NULL
    ,NOME_PRODUTO VARCHAR(45)
    ,PRECO DECIMAL
    ,PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE VENDA(
	IDPEDIDO INT NOT NULL
    ,IDPRODUTO INT NOT NULL
    ,PRIMARY KEY (IDPEDIDO, IDPRODUTO)
    ,FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (IDPEDIDO)
    ,FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
);